---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ19N18"
  stages:
    Acceptance:
      cfCredentialsId: "testdeploy"
    Release:
      cfCredentialsId: "testdeploy"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: " 15ee199btrial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "15ee199btrial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa"
    credentialsId: "ctmcredential"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
